db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=password
myapp:
  build: .
  volumes:
    - "./src:/src/app"
  links:
    - db
  environment:
    - PGHOST=db
    - PGDATABASE=postgres
    - PGUSER=postgres
    - PGPASSWORD=password
