db:
  build: ./postgres
  environment:
    - POSTGRES_PASSWORD=password
myapp:
  build: .
  volumes:
    - "./src:/src/app"
  ports:
      - "3000:3000"
  links:
    - db
  environment:
    - PGHOST=db
    - PGDATABASE=postgres
    - PGUSER=postgres
    - PGPASSWORD=password
